#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=$(getApplication)

runApplication fluentMeshToFoam -scale 0.001 berl.msh

runApplication XiFoam

#------------------------------------------------------------------------------
